name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v3

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/loom-cache
          key: ${{ runner.os }}-gradle-v2-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v2-

      - run: ./gradlew --no-daemon build
      - uses: actions/upload-artifact@v4
        with:
          name: PolyPatcher-1.8.9
          path: versions/1.8.9-forge/build/libs/PolyPatcher-1.8.9-forge-1.10.2.jar
          retention-days: 90
          compression-level: 9
      - run: ls versions/*/*/*
